export type Row = Record<string, any>;
export type ColumnInfo={name:string,type:'number'|'date'|'category'|'boolean'|'text';unique:number;missing:number;};
export type ChartConfig={id:string;title:string;kind:'line'|'bar'|'area'|'donut'|'scatter';x?:string;y?:string;group?:string;};
const isNum=(v:any)=>v!==null&&v!==''&&Number.isFinite(Number(v));
const isDate=(v:any)=>{if(v===null||v==='')return false; const d=new Date(v); return !Number.isNaN(d.getTime())&&/[\/-]|\d{4}/.test(String(v));};
export function profile(rows:Row[]):ColumnInfo[]{if(!rows.length)return[];return Object.keys(rows[0]).map(name=>{const vals=rows.map(r=>r[name]);const non=vals.filter(v=>v!==null&&v!==undefined&&v!=='');const numeric=non.filter(isNum).length;const dates=non.filter(isDate).length;let type:ColumnInfo['type']='text';if(numeric/non.length>.85)type='number';else if(dates/non.length>.85)type='date';else if([...new Set(non.map(String))].length<=12)type='category';return{name,type,unique:new Set(non.map(String)).size,missing:vals.length-non.length}})}
export function numCols(info:ColumnInfo[]){return info.filter(c=>c.type==='number')}
export function catCols(info:ColumnInfo[]){return info.filter(c=>c.type==='category'||c.type==='text')}
export function dateCols(info:ColumnInfo[]){return info.filter(c=>c.type==='date')}
export function summarize(rows:Row[], col:string){const a=rows.map(r=>Number(r[col])).filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;const sum=a.reduce((x,y)=>x+y,0),mean=sum/a.length;const q=(p:number)=>a[Math.min(a.length-1,Math.floor(p*(a.length-1)))];return{sum,mean,min:a[0],max:a[a.length-1],median:q(.5),p25:q(.25),p75:q(.75)}}
export function chooseMetrics(rows:Row[],info:ColumnInfo[]){const nums=numCols(info);const cats=catCols(info);const lower=(s:string)=>s.toLowerCase();const find=(words:string[])=>nums.find(c=>words.some(w=>lower(c.name).includes(w)));const revenue=find(['revenue','sales','amount','price','income','adr','spend','salary','profit']);const count=rows.length;const primary=revenue||nums[0];const metrics:any[]=[];if(primary){const s=summarize(rows,primary.name)!;metrics.push({label:primary.name,value:s.sum,format:'number'});}metrics.push({label:'Rows',value:count,format:'integer'});if(cats[0])metrics.push({label:cats[0].name,value:new Set(rows.map(r=>r[cats[0].name])).size,format:'integer'});if(nums[1]){const s=summarize(rows,nums[1].name)!;metrics.push({label:nums[1].name,value:s.sum,format:'number'});}return metrics.slice(0,4)}
export function chooseCharts(rows:Row[],info:ColumnInfo[]):ChartConfig[]{const nums=numCols(info),cats=catCols(info),dates=dateCols(info);const charts:ChartConfig[]=[];if(dates[0]&&nums[0])charts.push({id:'trend',title:`${nums[0].name} Trend`,kind:'line',x:dates[0].name,y:nums[0].name});if(cats[0]&&nums[0])charts.push({id:'category',title:`${nums[0].name} by ${cats[0].name}`,kind:'bar',x:cats[0].name,y:nums[0].name});if(nums.length>=2)charts.push({id:'relationship',title:`${nums[0].name} vs ${nums[1].name}`,kind:'scatter',x:nums[0].name,y:nums[1].name});if(cats[1]&&nums[0])charts.push({id:'segment',title:`${nums[0].name} by ${cats[1].name}`,kind:'donut',x:cats[1].name,y:nums[0].name});if(nums[0]&&nums[1])charts.push({id:'comparison',title:`${nums[1].name} Analysis`,kind:'area',x:cats[0]?.name||info[0]?.name,y:nums[1].name});return charts.slice(0,5)}
export function chartData(rows:Row[],cfg:ChartConfig){if(cfg.kind==='scatter')return rows.slice(0,1000).map(r=>({x:Number(r[cfg.x!]),y:Number(r[cfg.y!])})).filter(d=>Number.isFinite(d.x)&&Number.isFinite(d.y));const map=new Map<string,number>();for(const r of rows){const k=String(r[cfg.x!]??'Unknown');const v=Number(r[cfg.y!]);if(Number.isFinite(v))map.set(k,(map.get(k)||0)+v)}return [...map.entries()].map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value).slice(0,12)}
export function insights(rows:Row[],info:ColumnInfo[]){const nums=numCols(info),cats=catCols(info);const out:string[]=[];if(nums[0]){const s=summarize(rows,nums[0].name)!;out.push(`${nums[0].name} totals ${s.sum.toLocaleString(undefined,{maximumFractionDigits:2})}, with an average of ${s.mean.toLocaleString(undefined,{maximumFractionDigits:2})}.`)}if(cats[0]&&nums[0]){const m=new Map<string,number>();rows.forEach(r=>{const k=String(r[cats[0].name]??'Unknown'),v=Number(r[nums[0].name]);if(Number.isFinite(v))m.set(k,(m.get(k)||0)+v)});const top=[...m.entries()].sort((a,b)=>b[1]-a[1])[0];if(top)out.push(`${top[0]} is the leading ${cats[0].name} for ${nums[0].name}, contributing ${top[1].toLocaleString(undefined,{maximumFractionDigits:2})}.`)}if(info.some(c=>c.missing))out.push(`Data quality watch: ${info.filter(c=>c.missing).length} columns contain missing values and should be reviewed.`);return out}
export function formatValue(v:number){if(Math.abs(v)>=1e9)return`$${(v/1e9).toFixed(2)}B`;if(Math.abs(v)>=1e6)return`$${(v/1e6).toFixed(2)}M`;if(Math.abs(v)>=1e3)return`$${(v/1e3).toFixed(1)}K`;return v.toLocaleString(undefined,{maximumFractionDigits:2})}

export function askAI(question:string,rows:Row[],info:ColumnInfo[]){
  const q=question.trim().toLowerCase();
  if(!q)return 'Please enter a question about your uploaded dataset.';
  if(!rows.length)return 'There is no data available to analyze.';
  const nums=numCols(info),cats=catCols(info),dates=dateCols(info);
  const pickNum=(words:string[])=>nums.find(c=>words.some(w=>c.name.toLowerCase().includes(w)))||nums[0];
  const primary=pickNum(['sales','revenue','amount','value','price','income','spend','profit','adr','salary','score']);
  const category=cats.find(c=>['category','product','region','country','artist','segment','department','genre','type','name'].some(w=>c.name.toLowerCase().includes(w)))||cats[0];
  const money=(v:number)=>v.toLocaleString(undefined,{maximumFractionDigits:2});
  if(/top\s*10|highest|best|largest|maximum/.test(q)){
    const target=pickNum(q.includes('profit')?['profit']:q.includes('revenue')||q.includes('sales')?['revenue','sales','amount']:[]);
    if(category&&target){const map=new Map<string,number>();rows.forEach(r=>{const k=String(r[category.name]??'Unknown'),v=Number(r[target.name]);if(Number.isFinite(v))map.set(k,(map.get(k)||0)+v)});const top=[...map.entries()].sort((a,b)=>b[1]-a[1]).slice(0,10);if(top.length)return `Top ${Math.min(10,top.length)} ${category.name} by ${target.name}: ${top.map((x,i)=>`${i+1}. ${x[0]} (${money(x[1])})`).join(' · ')}`;}
  }
  if(q.includes('best month')||q.includes('month')){
    if(dates.length&&primary){const map=new Map<string,number>();rows.forEach(r=>{const d=new Date(r[dates[0].name]),v=Number(r[primary.name]);if(!Number.isNaN(d.getTime())&&Number.isFinite(v)){const k=d.toLocaleString(undefined,{month:'long',year:'numeric'});map.set(k,(map.get(k)||0)+v)}});const top=[...map.entries()].sort((a,b)=>b[1]-a[1])[0];if(top)return `Best month by ${primary.name}: ${top[0]} with ${money(top[1])}.`;}
  }
  if(/compare|vs|versus/.test(q)&&dates.length&&/20\d{2}/.test(q)){
    const years=[...q.matchAll(/20\d{2}/g)].map(m=>m[0]).slice(0,2);if(years.length===2&&primary){const sums=years.map(y=>rows.reduce((s,r)=>{const d=new Date(r[dates[0].name]),v=Number(r[primary.name]);return !Number.isNaN(d.getTime())&&String(d.getFullYear())===y&&Number.isFinite(v)?s+v:s},0));const diff=sums[1]-sums[0],pct=sums[0]?diff/sums[0]*100:0;return `${primary.name} comparison: ${years[0]} = ${money(sums[0])}, ${years[1]} = ${money(sums[1])}. ${years[1]} is ${Math.abs(pct).toFixed(1)}% ${diff>=0?'higher':'lower'} than ${years[0]}.`;}
  }
  if(q.includes('count')||q.includes('how many')||q.includes('number of')){if(category){const unique=new Set(rows.map(r=>String(r[category.name]??'Unknown')));return `There are ${unique.size.toLocaleString()} unique ${category.name} values across ${rows.length.toLocaleString()} rows.`;}return `The dataset contains ${rows.length.toLocaleString()} rows and ${info.length.toLocaleString()} columns.`;}
  if(q.includes('average')||q.includes('mean')){const target=pickNum(q.includes('profit')?['profit']:q.includes('sales')?['sales']:q.includes('revenue')?['revenue']:[]);if(target){const s=summarize(rows,target.name)!;return `Average ${target.name}: ${money(s.mean)} across ${rows.length.toLocaleString()} rows.`;}}
  if(q.includes('profit')&&primary){const profit=nums.find(c=>c.name.toLowerCase().includes('profit'));if(profit&&dates.length){const ordered=rows.map(r=>({d:new Date(r[dates[0].name]),v:Number(r[profit.name])})).filter(x=>!Number.isNaN(x.d.getTime())&&Number.isFinite(x.v)).sort((a,b)=>a.d.getTime()-b.d.getTime());if(ordered.length>3){const mid=Math.floor(ordered.length/2),a=ordered.slice(0,mid).reduce((s,x)=>s+x.v,0),b=ordered.slice(mid).reduce((s,x)=>s+x.v,0);return `Profit analysis: the first half totals ${money(a)} and the second half totals ${money(b)}. ${b<a?'Profit decreased':'Profit increased'} in the later period; check the date trend and related measures for the drivers.`;}}}
  if(primary){const s=summarize(rows,primary.name)!;return `Based on the uploaded dataset, ${primary.name} totals ${money(s.sum)} with an average of ${money(s.mean)}, a minimum of ${money(s.min)}, and a maximum of ${money(s.max)}. Ask about a category, product, region, month, or comparison for a more specific answer.`;}
  return `I found ${rows.length.toLocaleString()} rows and ${info.length.toLocaleString()} columns, but no numeric measure was detected for a calculated answer. Try asking about counts or categories.`;
}
